### ISSUE TITLE
Bundle State in Graph Object

### ISSUE THREAD

**Issue by WardCunningham** [WardCunningham/graph#3]
Our nodes and rels are closely linked in that their elements refer to each other by index. I don't see how we could go wrong by bundling them in a single Object.

I propose we create an ES6 object with methods necessary to past our existing tests. I don't see any immediate problem with the Object exposing the arrays that hold the nodes and rels, at least while we are experimenting. Better to provide methods that update these objects when they are changed. 

In federated wiki we often look for ways that work can be shared between sites and pages. A Graph object would be the first step in this direction since it would allow a script to hold two graphs at the same time.

**Comment by mkelleyharris** [comment]
I share your optimism for using a Graph class/object for reasons you stated. I'm less sure about exposing the state implementation directly (e.g. arrays) in the long run. It could be optional for now. Looking forward to seeing the tests use it either way.

**Comment by WardCunningham** [comment]
This is a function I found handy when adding elements to graphs or rels.
```
const tally = list => list.reduce((s,e)=>{s[e.type] = s[e.type] ? s[e.type]+1 : 1; return s}, {})
```

In use I would capture before and after counts.
```
let had = {nodes:tally(nodes), rels:tally(rels)}
...
let now = {nodes:tally(nodes), rels:tally(rels)}
```

A Graph might expose tally() as a function leaving it to a ui to render this in useful ways. I used a function that created an html report from the before and after counts.
```
  function diff (had, now) {
    let html = []
    for (let list of ['nodes', 'rels']) {
      for (let type in now[list]) {
        if((had[list][type]||0) != now[list][type])
          html.push(`${type}: ${now[list][type]-(had[list][type]||0)} ${list}`)
      }
    }
    return html.join("<br>")
  }
  ```

**Comment by mkelleyharris** [comment]
Brainstorming some names for graph elements:

graph nodes & rels, could be generically called: parts, pieces, or elements.   (e.g. Graph.size() could return number of parts. (nodes+links)  or Graph.sizeParts() could return number of parts)

node alternative names: point, actor, vertex, member, (e.g. Graph.sizeNodes() could return number of nodes)

rel alternative names: link, line, arcs, edge, tie
(e.g. Graph.sizeLinks() could return number of links)

size could be count.  Graph.countNodes() and Graph.countLinks()

Just brainstorming.
